// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Checkbox: typeof import('./components/ui/Checkbox.vue')['default']
    Drawer: typeof import('./components/ui/Drawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/Select.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarButton: typeof import('./components/SidebarButton.vue')['default']
  }
}
